version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      # These values should be set in the .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # PGDATA is set to ensure data persists in the named volume sub-directory
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Mounts the 'postgres-data' volume into the container
      - postgres-data:/var/lib/postgresql/data
    ports:
      # Exposes port 5432 internally within the Docker network
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  emailer:
    image: autonomactfregistry.azurecr.io/ctf/emailer:1.0.0
    container_name: emailer
    restart: unless-stopped
    ports:
      # Exposes port 8080 internally
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 64M

  ssh-app:
    image: autonomactfregistry.azurecr.io/ctf/ssh:1.0.14
    container_name: ssh-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      emailer:
        condition: service_started # Or service_healthy if emailer has a healthcheck
    ports:
      - "2222:2222"
    environment:
      TERM: "xterm-256color"
      COLORTERM: "truecolor"
      # These values should be set in the .env file or directly here if preferred
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      # Connects to the emailer service using its service name and internal port
      EMAILER_HOST: emailer:8080
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M

volumes:
  # Defines the named volume for Postgres data persistence
  postgres-data:
    driver: local # Default driver
