apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # echo -n 'your-postgres-password' | base64
  POSTGRES_PASSWORD: <base64-encoded-value>
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # echo -n 'your-resend-api-key' | base64
  RESEND_API_KEY: <base64-encoded-value>
  # echo -n 'postgresql://postgres:<your-postgres-password>@postgres-service:5432/postgres' | base64
  # Make sure the password here matches the one in postgres-secret and the service name matches the postgres service below.
  DATABASE_URL: <base64-encoded-value>
  # echo -n 'your-emailer-host:port' | base64 
  # Example: echo -n 'emailer-service:8080' | base64
  EMAILER_HOST: <base64-encoded-value>